<?php
$pageTitle = 'Home';
require __DIR__ . '/includes/header.php';
$stats = [
    'tutors' => (int)$pdo->query("SELECT COUNT(*) FROM tutor_profiles WHERE approval_status='approved'")->fetchColumn(),
    'tuitions' => (int)$pdo->query("SELECT COUNT(*) FROM tuition_posts WHERE status='approved'")->fetchColumn(),
    'users' => (int)$pdo->query("SELECT COUNT(*) FROM users WHERE status='active'")->fetchColumn(),
];
$latestTutors = $pdo->query("SELECT tp.*, u.name FROM tutor_profiles tp JOIN users u ON u.id=tp.user_id WHERE tp.approval_status='approved' AND u.status='active' ORDER BY tp.updated_at DESC LIMIT 3")->fetchAll();
$latestPosts = $pdo->query("SELECT t.*, u.name FROM tuition_posts t JOIN users u ON u.id=t.user_id WHERE t.status='approved' ORDER BY t.created_at DESC LIMIT 4")->fetchAll();
?>
<section class="hero">
<div class="container py-5"><div class="row align-items-center g-5 w-100"><div class="col-lg-7"><span class="badge text-bg-warning mb-3 px-3 py-2">Trusted tuition matching platform</span><h1 class="display-4 fw-bold">Find the right tutor.<br>Find the right tuition.</h1><p class="lead mt-3 text-white-50">A structured platform for students, guardians and tutors to connect by subject, class, location, schedule and salary.</p><div class="d-flex gap-3 flex-wrap mt-4"><a class="btn btn-warning btn-lg px-4" href="<?= url('tutors.php') ?>">Find a Tutor</a><a class="btn btn-outline-light btn-lg px-4" href="<?= url('tuitions.php') ?>">Browse Tuitions</a></div></div><div class="col-lg-5"><div class="hero-card p-4"><h4 class="fw-bold">Why Tuition Media?</h4><div class="mt-4"><p>✓ Role-based dashboard</p><p>✓ Search and filters</p><p>✓ Application status tracking</p><p>✓ Tutor availability</p><p>✓ Reviews and notifications</p></div></div></div></div></div>
</section>
<section class="container py-5"><div class="row g-4 text-center"><div class="col-md-4"><div class="card stat-card shadow-soft p-4"><div class="display-6 fw-bold"><?= $stats['tutors'] ?>+</div><div class="text-muted">Approved Tutors</div></div></div><div class="col-md-4"><div class="card stat-card shadow-soft p-4"><div class="display-6 fw-bold"><?= $stats['tuitions'] ?>+</div><div class="text-muted">Active Tuition Posts</div></div></div><div class="col-md-4"><div class="card stat-card shadow-soft p-4"><div class="display-6 fw-bold"><?= $stats['users'] ?>+</div><div class="text-muted">Registered Users</div></div></div></div></section>
<section class="container py-4"><div class="d-flex justify-content-between align-items-end mb-3"><div><h2 class="section-title">Featured Tutors</h2><p class="text-muted mb-0">Recently updated approved profiles</p></div><a href="<?= url('tutors.php') ?>">View all</a></div><div class="row g-4"><?php foreach($latestTutors as $t): ?><div class="col-md-4"><div class="card shadow-soft h-100 p-4"><div class="d-flex gap-3 align-items-center"><div class="avatar-circle"><?= e(strtoupper(substr($t['name'],0,1))) ?></div><div><h5 class="mb-1"><?= e($t['name']) ?></h5><small class="text-muted"><?= e($t['education']) ?></small></div></div><hr><p><strong>Subjects:</strong> <?= e($t['subjects']) ?></p><p><strong>Area:</strong> <?= e($t['location']) ?></p><p><strong>Expected:</strong> ৳<?= number_format((float)$t['expected_salary']) ?></p><a class="btn btn-outline-primary mt-auto" href="<?= url('tutor_view.php?id='.$t['id']) ?>">View Profile</a></div></div><?php endforeach; ?></div></section>
<section class="container py-5"><div class="d-flex justify-content-between align-items-end mb-3"><div><h2 class="section-title">Latest Tuition Opportunities</h2><p class="text-muted mb-0">Approved requirements from students and guardians</p></div><a href="<?= url('tuitions.php') ?>">View all</a></div><div class="row g-4"><?php foreach($latestPosts as $p): ?><div class="col-md-6"><div class="card shadow-soft h-100 p-4"><div class="d-flex justify-content-between"><span class="badge text-bg-info"><?= e($p['subject']) ?></span><?= status_badge($p['status']) ?></div><h4 class="mt-3"><?= e($p['title']) ?></h4><p class="text-muted mb-2"><?= e($p['class_level']) ?> • <?= e($p['location']) ?> • <?= e($p['teaching_mode']) ?></p><p>Salary: ৳<?= number_format((float)$p['salary_min']) ?>–৳<?= number_format((float)$p['salary_max']) ?></p><a class="btn btn-outline-primary" href="<?= url('tuition_view.php?id='.$p['id']) ?>">View Details</a></div></div><?php endforeach; ?></div></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
